{% set version = "2.13.02" %}

package:
  name: nasm
  version: {{ version }}

source:
  fn: nasm-{{ version }}.tar.gz
  url: http://www.nasm.us/pub/nasm/releasebuilds/{{ version }}/nasm-{{ version }}.tar.gz
  sha256: 4749fd76a8a26dc7d8871bc97cc2c16cfa0c933f984a13128e94f464f417531a

build:
  number: 1001
  skip: true  # [win and vc<14]

requirements:
  build:
    - {{ compiler('c') }}
    - make  # [unix]
  host:

test:
  commands:
    - nasm -h
    - nasm -version
    - ndisasm -h

about:
  home: http://www.nasm.us
  license: BSD 2-Clause
  license_file: LICENSE
  summary: "Netwide Assembler: an assembler targetting the Intel x86 series of processors."

extra:
  recipe-maintainers:
    - jakirkham
